# 只需要登录不需要权限的路由
publicRoutes:
  "/auth/reset-password": "POST"
  "/auth/profile": "GET"

# 不需要鉴权的接口
ignoreRoutes:
  "/auth/login":  "POST"
  "/auth/captcha": "GET"

# TokenHeader 登录后返回的 token 头信息
TokenHeader: X-Token

# ctx user 上下文key
CtxUserKey: Admin-User-Id
