// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf-ant-react/internal/dao/internal"
)

// cmsSiteSettingDao is the data access object for the table cms_site_setting.
// You can define custom methods on it to extend its functionality as needed.
type cmsSiteSettingDao struct {
	*internal.CmsSiteSettingDao
}

var (
	// CmsSiteSetting is a globally accessible object for table cms_site_setting operations.
	CmsSiteSetting = cmsSiteSettingDao{internal.NewCmsSiteSettingDao()}
)

// Add your custom methods and functionality below.
