// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf-ant-react/internal/dao/internal"
)

// sysDepartmentsDao is the data access object for the table sys_departments.
// You can define custom methods on it to extend its functionality as needed.
type sysDepartmentsDao struct {
	*internal.SysDepartmentsDao
}

var (
	// SysDepartments is a globally accessible object for table sys_departments operations.
	SysDepartments = sysDepartmentsDao{internal.NewSysDepartmentsDao()}
)

// Add your custom methods and functionality below.
