// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf-ant-react/internal/dao/internal"
)

// sysUsersDao is the data access object for the table sys_users.
// You can define custom methods on it to extend its functionality as needed.
type sysUsersDao struct {
	*internal.SysUsersDao
}

var (
	// SysUsers is a globally accessible object for table sys_users operations.
	SysUsers = sysUsersDao{internal.NewSysUsersDao()}
)

// Add your custom methods and functionality below.
