// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf-ant-react/internal/dao/internal"
)

// sysApisDao is the data access object for the table sys_apis.
// You can define custom methods on it to extend its functionality as needed.
type sysApisDao struct {
	*internal.SysApisDao
}

var (
	// SysApis is a globally accessible object for table sys_apis operations.
	SysApis = sysApisDao{internal.NewSysApisDao()}
)

// Add your custom methods and functionality below.
