// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf-ant-react/internal/dao/internal"
)

// sysUserRolesDao is the data access object for the table sys_user_roles.
// You can define custom methods on it to extend its functionality as needed.
type sysUserRolesDao struct {
	*internal.SysUserRolesDao
}

var (
	// SysUserRoles is a globally accessible object for table sys_user_roles operations.
	SysUserRoles = sysUserRolesDao{internal.NewSysUserRolesDao()}
)

// Add your custom methods and functionality below.
