// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf-ant-react/internal/dao/internal"
)

// sysRolesDao is the data access object for the table sys_roles.
// You can define custom methods on it to extend its functionality as needed.
type sysRolesDao struct {
	*internal.SysRolesDao
}

var (
	// SysRoles is a globally accessible object for table sys_roles operations.
	SysRoles = sysRolesDao{internal.NewSysRolesDao()}
)

// Add your custom methods and functionality below.
