// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf-ant-react/internal/dao/internal"
)

// sysFileUploadDao is the data access object for the table sys_file_upload.
// You can define custom methods on it to extend its functionality as needed.
type sysFileUploadDao struct {
	*internal.SysFileUploadDao
}

var (
	// SysFileUpload is a globally accessible object for table sys_file_upload operations.
	SysFileUpload = sysFileUploadDao{internal.NewSysFileUploadDao()}
)

// Add your custom methods and functionality below.
