// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf-ant-react/internal/dao/internal"
)

// sysRoleApisDao is the data access object for the table sys_role_apis.
// You can define custom methods on it to extend its functionality as needed.
type sysRoleApisDao struct {
	*internal.SysRoleApisDao
}

var (
	// SysRoleApis is a globally accessible object for table sys_role_apis operations.
	SysRoleApis = sysRoleApisDao{internal.NewSysRoleApisDao()}
)

// Add your custom methods and functionality below.
